name: 'ZenHub link PR to issue'
description: 'Create ZenHub link between pull request and issue based on the branch prefix'
author: 'CoBloX Team'
branding:
  icon: git-pull-request
  color: purple
inputs:
  ZENHUB_TOKEN:
    description: 'A ZenHub API token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
